### ISSUE TITLE
Continuous crashing of bot

### ISSUE THREAD

**Issue by JesseFST** [sedmelluq/lavaplayer#162]
This has happened since recent update in Lavaplayer.
Here's the crash log: 
https://pastebin.com/A26vRqXh

**Comment by nikammerlaan** [comment]
I'm getting the same issue here, also on OpenJDK 11.0.2

**Comment by LogalDeveloper** [comment]
I am encountering this issue as well.
```
JRE version: OpenJDK Runtime Environment (8.0_191-b12) (build 1.8.0_191-8u191-b12-2ubuntu0.18.04.1-b12)
Java VM: OpenJDK 64-Bit Server VM (25.191-b12 mixed mode linux-amd64 compressed oops)
Problematic frame:
C  [libconnector.so+0x171b7f]
```

**Comment by Nesz** [comment]
Same here 

```
A fatal error has been detected by the Java Runtime Environment:

SIGSEGV (0xb) at pc=0x00007ff8b64a1b64, pid=28693, tid=0x00007ff8b5a55700

JRE version: Java(TM) SE Runtime Environment (8.0_201-b09) (build 1.8.0_201-b09)
Java VM: Java HotSpot(TM) 64-Bit Server VM (25.201-b09 mixed mode linux-amd64 compressed oops)
Problematic frame:
C  [libconnector.so+0x171b64]
```

**Comment by sedmelluq** [comment]
Should be fixed in `1.3.12`. Will keep it open for a while to see if there are any more reports.

**Comment by IamTails** [comment]
This is still occurring with 1.3.12

**Comment by nikammerlaan** [comment]
Can definitely confirm -- still occurring with 1.3.12
https://gist.github.com/nikammerlaan/988a65ccf44a46a1b2c4ab38dfb3a770

**Comment by sedmelluq** [comment]
According to the addresses in those logs you're both still running natives from `1.3.11`. 🤔

**Comment by LogalDeveloper** [comment]
This issue seems to be fixed in my development environment using the latest version, however I'm not going to upgrade in production quite yet until maybe a few more people say things are fine here.

**Comment by Nesz** [comment]
No crashes occurred since update to `1.3.12` I guess its fixed

**Comment by sedmelluq** [comment]
Apparently LP 1.3.12 included the old Linux native library in its own JAR in addition to including natives with the fixed version as a dependency. Therefore it may have been up to chance if you got the fixed version or not. 1.3.13 definitely has no traces of the broken one left.

**Comment by IamTails** [comment]
I can confirm 1.3.13 fixes, thanks

**Comment by sedmelluq** [comment]
Seems to be resolved, closing.

**Comment by KleinDevDE** [comment]
Hey Guys,

Sorry for reopening this ticket.
I'm also having this problem.

My specs:
```
// build.gradle
compile 'org.javacord:javacord:3.3.0'
compile 'com.sedmelluq:lavaplayer:1.3.75'

// The OS
Debian bullseye/sid
Kernel version: 5.4
CPU: AMD EPYC 7351P 16-Core Processor
RAM: 12GB
SWAP: 2GB
ROM: 110GB

// Java
openjdk version "14.0.2" 2020-07-14
OpenJDK Runtime Environment (build 14.0.2+12-Ubuntu-120.04)
OpenJDK 64-Bit Server VM (build 14.0.2+12-Ubuntu-120.04, mixed mode, sharing)

// Start command
screen -L -dmS Loki /usr/lib/jvm/java-14-openjdk-amd64/bin/java -jar $1
```

What I tried:
```java
// Playing 24/7 an radio stream.
        ServerVoiceChannel serverVoiceChannel = Loki.getInstance().getDiscordApi().getServerVoiceChannelById(voiceChannelID).get();
        if (!serverVoiceChannel.canYouConnect()) {
            Logger.error("Can't connect to the voice channel!");
            return;
        }

        audioConnection = serverVoiceChannel.connect().join();
        audioConnection.setSelfDeafened(true);
        audioConnection.setPrioritySpeaking(true);
        AudioPlayerManager audioPlayerManager = new DefaultAudioPlayerManager();
        AudioPlayer audioPlayer = audioPlayerManager.createPlayer();
        HttpAudioSourceManager httpAudioSourceManager = new HttpAudioSourceManager();
        audioPlayerManager.registerSourceManager(httpAudioSourceManager);

        AudioSource source = new LavaplayerAudioSource(Loki.getInstance().getDiscordApi(), audioPlayer);
        audioConnection.setAudioSource(source);
        audioPlayerManager.loadItem("XXXX/XX.mp3", new AudioLoadResultHandler() {
            @Override
            public void trackLoaded(AudioTrack track) {
                audioPlayer.playTrack(track);
            }

            @Override
            public void playlistLoaded(AudioPlaylist playlist) {
                for (AudioTrack track : playlist.getTracks()) {
                    audioPlayer.playTrack(track);
                }
            }

            @Override
            public void noMatches() {
                Logger.info("noMatches");
            }

            @Override
            public void loadFailed(FriendlyException throwable) {
                Logger.error("loadFailed");
                throwable.printStackTrace();
            }
        });
```
The LavaplayerAudioSource:
[LavaplayerAudioSource.txt](https://github.com/sedmelluq/lavaplayer/files/6403683/LavaplayerAudioSource.txt)

The hs_err
[hs_err_pid11624.log](https://github.com/sedmelluq/lavaplayer/files/6403672/hs_err_pid11624.log)
